import json
import os

GLOSSARY_PATH = "translation_patch/glossary.json"

# Common translations map
MAPPINGS = {
    "验证码不能为空": "O código de verificação não pode estar vazio",
    "请输入正确的手机号码": "Insira um número de celular correto",
    "智能体管理": "Gestão de Agentes",
    "音色克隆": "Clonagem de Voz",
    "音色资源": "Recursos de Voz",
    "模型配置": "Configuração de Modelos",
    "知识库": "Base de Conhecimento",
    "用户管理": "Gestão de Usuários",
    "OTA管理": "Gestão de OTA",
    "参数字典": "Dicionário de Parâmetros",
    "参数管理": "Gestão de Parâmetros",
    "字典管理": "Gestão de Dicionário",
    "默认角色模板": "Modelo de Papel Padrão",
    "搜索历史": "Histórico de Busca",
    "清空历史": "Limpar Histórico",
    "字段管理": "Gestão de Campos",
    "服务端管理": "Gestão do Servidor",
    "系统功能配置": "Configuração de Funções do Sistema",
    "修改密码": "Alterar Senha",
    "退出登录": "Sair",
    "工具调用": "Chamada de Ferramenta",
    "执行": "Executar",
    "取消": "Cancelar",
    "确定": "Confirmar",
    "保存": "Salvar",
    "删除": "Excluir",
    "编辑": "Editar",
    "新增": "Novo",
    "搜索": "Buscar",
    "加载中": "Carregando",
    "成功": "Sucesso",
    "失败": "Falha",
    "音量": "Volume",
    "亮度": "Brilho",
    "主题": "Tema",
    "重启": "Reiniciar",
    "固件": "Firmware",
    "版本": "Versão",
    "网络": "Rede",
    "状态": "Status",
    "在线": "Online",
    "离线": "Offline",
    "用户名": "Usuário",
    "密码": "Senha",
    "手机号": "Celular",
    "验证码": "Código",
    "登录": "Login",
    "注册": "Registro",
    "备注": "Observação",
    "首页": "Início",
    "设置": "Configurações",
    "帮助": "Ajuda",
    "关于": "Sobre",
    "查看设备状态": "Ver Status do Dispositivo",
    "设置音量": "Ajustar Volume",
    "设置亮度": "Ajustar Brilho",
    "设置主题": "Definir Tema",
    "拍照识别": "Tirar Foto e Identificar",
    "系统信息": "Informações do Sistema",
    "重启设备": "Reiniciar Dispositivo",
    "升级固件": "Atualizar Firmware",
    "屏幕信息": "Informações da Tela",
    "屏幕截图": "Captura de Tela",
    "设置下载地址": "Definir URL de Download",
    "预览图片": "Pré-visualizar Imagem",
    "音频": "Áudio",
    "显示": "Exibição",
    "拍摄": "Captura",
    "设备信息": "Informações do Dispositivo",
    "音频扬声器": "Alto-falante",
    "屏幕": "Tela",
    "硬件信息": "Informações de Hardware",
    "内存信息": "Informações de Memória",
    "应用信息": "Informações do Aplicativo",
    "网络信息": "Informações de Rede",
    "显示信息": "Informações de Exibição",
    "组件": "Componente",
    "属性": "Propriedade",
    "值": "Valor",
    "类型": "Tipo",
    "SSID": "SSID",
    "信号强度": "Força do Sinal",
    "操作结果": "Resultado da Operação",
    "宽度": "Largura",
    "高度": "Altura",
    "芯片型号": "Modelo do Chip",
    "CPU核心数": "Núcleos de CPU",
    "芯片版本": "Versão do Chip",
    "Flash大小": "Tamanho da Flash",
    "最小可用堆": "Mínimo Heap Livre",
    "应用名称": "Nome do App",
    "应用版本": "Versão do App",
    "编译时间": "Hora da Compilação",
    "IDF版本": "Versão do IDF",
    "MAC地址": "Endereço MAC",
    "IP地址": "Endereço IP",
    "WiFi名称": "Nome do WiFi",
    "WiFi信道": "Canal WiFi",
    "屏幕尺寸": "Tamanho da Tela",
    "设备UUID": "UUID do Dispositivo",
    "系统语言": "Idioma do Sistema",
    "当前OTA分区": "Partição OTA Atual",
    "URL": "URL",
    "质量": "Qualidade",
    "问题": "Pergunta",
    "强": "Forte",
    "中": "Médio",
    "弱": "Fraco",
    "深色": "Escuro",
    "浅色": "Claro",
    "设置成功": "Configurado com Sucesso",
    "设置失败": "Falha na Configuração",
    "重启指令已发送": "Comando de reinicialização enviado",
    "重启失败": "Falha ao reiniciar",
    "单色屏": "Tela Monocromática",
    "彩色屏": "Tela Colorida",
    "获取失败": "Falha na obtenção",
    "新增字典数据": "Novo dado de dicionário",
    "字典标签": "Rótulo do dicionário",
    "请输入字典标签": "Insira o rótulo do dicionário",
    "字典值": "Valor do dicionário",
    "请输入字典值": "Insira o valor do dicionário",
    "排序": "Ordenação",
    "新增字典类型": "Novo tipo de dicionário",
    "字典类型名称": "Nome do tipo de dicionário",
    "字典类型编码": "Código do tipo de dicionário",
    "音色编码": "Código da voz",
    "音色名称": "Nome da voz",
    "语言类型": "Tipo de idioma",
    "中文": "Chinês",
    "英文": "Inglês",
    "获取成功，但解析失败": "Obtido com sucesso, mas falha na análise",
    "获取成功，但数据格式异常": "Obtido com sucesso, mas formato de dados inválido",
    "固件名称": "Nome do Firmware",
    "请输入固件名称(板子+版本号)": "Insira o nome do firmware (placa + versão)",
    "固件类型": "Tipo de Firmware",
    "请选择固件类型": "Selecione o tipo de firmware",
    "版本号": "Versão",
    "请输入版本号(x.x.x格式)": "Insira o número da versão (formato x.x.x)",
    "固件文件": "Arquivo de Firmware",
    "点击上传": "Clique para enviar",
    "只能上传固件文件(.bin/.apk)，且不超过100MB": "Apenas arquivos .bin/.apk (máx. 100MB)",
    "请输入备注信息": "Insira as observações",
    "请输入版本号": "Insira o número da versão",
    "版本号格式不正确，请输入x.x.x格式": "Formato inválido. Use x.x.x",
    "请上传固件文件": "Envie o arquivo do firmware",
    "固件文件上传成功": "Firmware enviado com sucesso",
    "文件上传失败": "Falha no envio do arquivo",
    "添加说话人": "Adicionar falando",
    "姓名": "Nome",
    "请输入姓名": "Insira o nome",
    "描述": "Descrição",
    "请输入描述": "Insira a descrição",
    "确定": "Confirmar",
    "取消": "Cancelar",
    "保存": "Salvar",
    "删除": "Excluir",
    "编辑": "Editar",
    "新增": "Novo",
    "搜索": "Buscar",
    "加载中": "Carregando",
    "成功": "Sucesso",
    "失败": "Falha",
    "音量": "Volume",
    "亮度": "Brilho",
    "主题": "Tema",
    "重启": "Reiniciar",
    "固件": "Firmware",
    "版本": "Versão",
    "网络": "Rede",
    "状态": "Status",
    "在线": "Online",
    "离线": "Offline",
    "用户名": "Usuário",
    "密码": "Senha",
    "手机号": "Celular",
    "验证码": "Código",
    "登录": "Login",
    "注册": "Registro",
    "备注": "Observação",
    "首页": "Início",
    "设置": "Configurações",
    "帮助": "Ajuda",
    "关于": "Sobre",
    "欢迎使用": "Bem-vindo",
    "重置密码": "Redefinir Senha",
    "验证码发送成功": "Código enviado com sucesso",
    "两次输入的密码不一致": "As senhas não coincidem",
    "获取验证码": "Obter Código",
    "正在加载中": "Carregando...",
    "确认要删除吗": "Confirmar exclusão?",
    "全选": "Selecionar Tudo",
    "操作成功": "Operação realizada com sucesso",
    "提示": "Dica",
    "清除缓存": "Limpar Cache",
    "刷新页面": "Atualizar página",
    "暂无数据": "Sem dados",
    "创建时间": "Data de Criação",
    "操作": "Ações",
    "返回": "Voltar",
    "你好小智": "Olá Xiaozhi",
    "配置角色": "Configurar Papel",
    "查看设备的当前运行状态，包括音量、屏幕、电池等信息。": "Veja o status de execução atual do dispositivo, incluindo volume, tela, bateria, etc.",
    "调整设备的音量大小，请输入0-100之间的数值。": "Ajuste o volume do dispositivo. Insira um valor entre 0 e 100.",
    "调整设备屏幕的亮度，请输入0-100之间的数值。": "Ajuste o brilho da tela. Insira um valor entre 0 e 100.",
    "切换设备屏幕的显示主题，可以选择浅色或深色模式。": "Alterne o tema da tela entre os modos claro ou escuro.",
    "使用设备摄像头拍摄照片并进行识别分析，请输入要询问的问题。": "Use a câmera para tirar uma foto e analisar. Insira sua pergunta.",
    "获取设备的系统信息，包括硬件规格、软件版本等。": "Obtenha informações do sistema, como especificações de hardware e versão de software.",
    "重启设备，执行后设备将重新启动。": "Reinicie o dispositivo.",
    "从指定URL下载并升级设备固件，升级后设备会自动重启。": "Baixe e atualize o firmware via URL. O dispositivo reiniciará após a conclusão.",
    "获取屏幕的详细信息，如分辨率、尺寸等参数。": "Obtenha detalhes da tela, como resolução e tamanho.",
    "对当前屏幕进行截图并上传到指定URL。": "Capture a tela e envie para uma URL específica.",
    "在设备屏幕上预览指定URL的图片。": "Pré-visualize uma imagem na tela do dispositivo via URL.",
    "设置设备资源文件的下载地址。": "Configure a URL para download de arquivos de recursos.",
    "请输入用户名": "Insira o nome de usuário",
    "请输入手机号码": "Insira o número de celular",
    "请输入验证码": "Insira o código de verificação",
    "请设置密码": "Defina a senha",
    "请确认密码": "Confirme a senha",
    "注册成功！": "Registro realizado com sucesso!",
    "密码长度必须在6-20位之间": "A senha deve ter entre 6 e 20 caracteres",
    "两次输入的密码不一致": "As senhas não coincidem",
    "忘记密码": "Esqueci a senha",
    "重置密码": "Redefinir senha",
    "立即修改": "Alterar agora",
    "旧密码": "Senha antiga",
    "新密码": "Nova senha",
    "确认新密码": "Confirme a nova senha",
    "设备管理": "Gestão de Dispositivos",
    "添加设备": "Adicionar Dispositivo",
    "解绑": "Desvincular",
    "在线": "Online",
    "离线": "Offline",
    "刚刚": "Agora mesmo",
    "{minutes}分钟前": "{minutes} minutos atrás",
    "{hours}小时{minutes}分钟前": "{hours} horas e {minutes} minutos atrás",
    "今天": "Hoje",
    "昨天": "Ontem",
    "加载中...": "Carregando...",
    "没有更多记录了": "Não há mais registros",
    "请选择会话查看聊天记录": "Selecione uma conversa para ver o histórico",
    "删除成功": "Excluído com sucesso",
    "保存成功": "Salvo com sucesso",
    "操作成功": "Operação realizada com sucesso",
    "操作失败": "Falha na operação",
    "注册时间": "Data de Registro",
    "用户Id": "ID do Usuário",
    "设备数量": "Qtd de Dispositivos",
    "正常": "Normal",
    "禁用": "Desativado",
    "启用": "Ativado",
    "删除用户": "Excluir Usuário",
    "禁用账户": "Desativar Conta",
    "恢复账号": "Restaurar Conta",
    "确定要删除该用户吗？": "Tem certeza que deseja excluir este usuário?",
    "正在删除中...": "Excluindo...",
    "删除过程中发生错误": "Ocorreu um erro durante a exclusão",
    "已取消删除": "Exclusão cancelada",
    "重置后将会生成新密码，是否继续？": "Uma nova senha será gerada após a redefinição. Continuar?",
    "密码已重置，请通知用户使用新密码登录": "Senha redefinida. Informe ao usuário a nova senha para login.",
    "生成的默认密码": "Senha padrão gerada",
    "修改成功": "Alterado com sucesso",
    "新增成功": "Adicionado com sucesso",
    "帮助": "Ajuda",
    "关于": "Sobre",
    "提示": "Dica",
    "警告": "Aviso",
    "确定": "Confirmar",
    "取消": "Cancelar",
    "关闭": "Fechar",
    "刷新页面": "Atualizar página",
    "清除缓存": "Limpar Cache",
    "缓存已清除": "Cache limpo",
    "正在刷新缓存状态": "Atualizando status do cache",
    "确定要清除所有缓存吗?": "Tem certeza que deseja limpar todo o cache?",
    "JavaScript 资源 ({count})": "Recursos JavaScript ({count})",
    "CSS 资源 ({count})": "Recursos CSS ({count})",
    "已缓存": "Em cache",
    "未缓存": "Não cacheado",
    "刷新缓存状态": "Atualizar status do cache",
    "共发现 {count} 个缓存资源": "Encontrados {count} recursos em cache",
    "中文简体": "Chinês Simplificado",
    "中文繁體": "Chinês Tradicional",
    "English": "Inglês",
    "Deutsch": "Alemão",
    "Tiếng Việt": "Vietnamita",
    "添加智能体": "Adicionar Agente",
    "让我们度过美好的一天！": "Vamos ter um ótimo dia!",
    "语言模型": "Modelo de Linguagem",
    "音色模型": "Modelo de Voz",
    "聊天记录": "Histórico de Chat",
    "最近对话": "Conversas Recentes",
    "暂未对话": "Nenhuma conversa ainda",
    "确定要删除该智能体吗？": "Tem certeza que deseja excluir este agente?",
    "删除失败": "Falha ao excluir",
    "配置角色": "Configurar Papel",
    "开启记忆": "Ativar Memória",
    "类别": "Categoria",
    "供应器编码": "Código do Provedor",
    "字段配置": "Configuração de Campos",
    "查看字段": "Ver Campos",
    "名称": "Nome",
    "全部": "Todos",
    "供应器名称": "Nome do Provedor",
    "参数": "Parâmetro",
    "参数编码": "Código do Parâmetro",
    "参数值": "Valor do Parâmetro",
    "备注": "Observação",
    "隐藏": "Ocultar",
    "查看": "Ver",
    "新增参数": "Novo Parâmetro",
    "编辑参数": "Editar Parâmetro",
    "获取参数列表失败": "Falha ao obter lista de parâmetros",
    "字典": "Dicionário",
    "字典标签": "Rótulo do Dicionário",
    "字典值": "Valor do Dicionário",
    "排序": "Ordem",
    "系统管理": "Gestão do Sistema",
    "日志管理": "Gestão de Logs",
    "文件管理": "Gestão de Arquivos",
    "定时任务": "Tarefas Agendadas",
    "说话人": "Falante",
    "声纹向量": "Vetor de Voz",
    "创建时间": "Data de Criação",
    "操作": "Ações",
    "首页": "Início",
    "上一页": "Anterior",
    "下一页": "Próxima",
    "确定要删除选中的此声纹吗？": "Tem certeza que deseja excluir esta voz selecionada?",
    "成功删除此声纹": "Voz excluída com sucesso",
    "拼命加载中": "Carregando a todo vapor...",
    "设备型号": "Modelo do Dispositivo",
    "固件版本": "Versão do Firmware",
    "Mac地址": "Endereço MAC",
    "设备添加成功": "Dispositivo adicionado com sucesso",
    "欢迎使用小智AI": "Bem-vindo ao Xiaozhi AI",
}

def translate():
    if not os.path.exists(GLOSSARY_PATH):
        print("Glossary not found")
        return

    with open(GLOSSARY_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    zh_cn = data.get("zh_CN", {})
    count = 0
    for key, val in zh_cn.items():
        if val == "TODO" or not val:
            # Try to translate using mappings
            # If it's a long string, we might need LLM, but for now let's do common ones
            if key in MAPPINGS:
                zh_cn[key] = MAPPINGS[key]
                count += 1
            else:
                # Placeholder for common patterns or just simple translation
                pass
    
    with open(GLOSSARY_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Translated {count} strings using local mappings.")

if __name__ == "__main__":
    translate()
