import json
import os

GLOSSARY_PATH = "translation_patch/glossary.json"

# Common translations map
MAPPINGS = {
    "验证码不能为空": "O código de verificação não pode estar vazio",
    "请输入正确的手机号码": "Insira um número de celular correto",
    "智能体管理": "Gestão de Agentes",
    "音色克隆": "Clonagem de Voz",
    "音色资源": "Recursos de Voz",
    "模型配置": "Configuração de Modelos",
    "知识库": "Base de Conhecimento",
    "用户管理": "Gestão de Usuários",
    "OTA管理": "Gestão de OTA",
    "参数字典": "Dicionário de Parâmetros",
    "参数管理": "Gestão de Parâmetros",
    "字典管理": "Gestão de Dicionário",
    "默认角色模板": "Modelo de Papel Padrão",
    "搜索历史": "Histórico de Busca",
    "清空历史": "Limpar Histórico",
    "字段管理": "Gestão de Campos",
    "服务端管理": "Gestão do Servidor",
    "系统功能配置": "Configuração de Funções do Sistema",
    "修改密码": "Alterar Senha",
    "退出登录": "Sair",
    "工具调用": "Chamada de Ferramenta",
    "执行": "Executar",
    "取消": "Cancelar",
    "确定": "Confirmar",
    "保存": "Salvar",
    "删除": "Excluir",
    "编辑": "Editar",
    "新增": "Novo",
    "搜索": "Buscar",
    "加载中": "Carregando",
    "成功": "Sucesso",
    "失败": "Falha",
    "音量": "Volume",
    "亮度": "Brilho",
    "主题": "Tema",
    "重启": "Reiniciar",
    "固件": "Firmware",
    "版本": "Versão",
    "网络": "Rede",
    "状态": "Status",
    "在线": "Online",
    "离线": "Offline",
    "用户名": "Usuário",
    "密码": "Senha",
    "手机号": "Celular",
    "验证码": "Código",
    "登录": "Login",
    "注册": "Registro",
    "备注": "Observação",
    "首页": "Início",
    "设置": "Configurações",
    "帮助": "Ajuda",
    "关于": "Sobre",
    "查看设备状态": "Ver Status do Dispositivo",
    "设置音量": "Ajustar Volume",
    "设置亮度": "Ajustar Brilho",
    "设置主题": "Definir Tema",
    "拍照识别": "Tirar Foto e Identificar",
    "系统信息": "Informações do Sistema",
    "重启设备": "Reiniciar Dispositivo",
    "升级固件": "Atualizar Firmware",
    "屏幕信息": "Informações da Tela",
    "屏幕截图": "Captura de Tela",
    "预览图片": "Pré-visualizar Imagem",
    "音频": "Áudio",
    "显示": "Exibição",
    "拍摄": "Captura",
    "设备信息": "Informações do Dispositivo",
    "音频扬声器": "Alto-falante",
    "屏幕": "Tela",
    "硬件信息": "Informações de Hardware",
    "内存信息": "Informações de Memória",
    "应用信息": "Informações do Aplicativo",
    "网络信息": "Informações de Rede",
    "显示信息": "Informações de Exibição",
    "组件": "Componente",
    "属性": "Propriedade",
    "值": "Valor",
    "类型": "Tipo",
    "SSID": "SSID",
    "信号强度": "Força do Sinal",
    "操作结果": "Resultado da Operação",
    "宽度": "Largura",
    "高度": "Altura",
    "芯片型号": "Modelo do Chip",
    "CPU核心数": "Núcleos de CPU",
    "芯片版本": "Versão do Chip",
    "Flash大小": "Tamanho da Flash",
    "最小可用堆": "Mínimo Heap Livre",
    "应用名称": "Nome do App",
    "应用版本": "Versão do App",
    "编译时间": "Hora da Compilação",
    "IDF版本": "Versão do IDF",
    "MAC地址": "Endereço MAC",
    "IP地址": "Endereço IP",
    "WiFi名称": "Nome do WiFi",
    "WiFi信道": "Canal WiFi",
    "屏幕尺寸": "Tamanho da Tela",
    "设备UUID": "UUID do Dispositivo",
    "系统语言": "Idioma do Sistema",
    "当前OTA分区": "Partição OTA Atual",
    "URL": "URL",
    "质量": "Qualidade",
    "问题": "Pergunta",
    "强": "Forte",
    "中": "Médio",
    "弱": "Fraco",
    "深色": "Escuro",
    "浅色": "Claro",
    "设置成功": "Configurado com Sucesso",
    "设置失败": "Falha na Configuração",
    "重启指令已发送": "Comando de reinicialização enviado",
    "重启失败": "Falha ao reiniciar",
    "单色屏": "Tela Monocromática",
    "彩色屏": "Tela Colorida",
    "获取失败": "Falha na obtenção",
    "新增字典数据": "Novo dado de dicionário",
    "字典标签": "Rótulo do dicionário",
    "请输入字典标签": "Insira o rótulo do dicionário",
    "字典值": "Valor do dicionário",
    "请输入字典值": "Insira o valor do dicionário",
    "排序": "Ordenação",
    "新增字典类型": "Novo tipo de dicionário",
    "字典类型名称": "Nome do tipo de dicionário",
    "字典类型编码": "Código do tipo de dicionário",
    "音色编码": "Código da voz",
    "音色名称": "Nome da voz",
    "语言类型": "Tipo de idioma",
    "中文": "Chinês",
    "英文": "Inglês",
    "确定": "Confirmar",
"取消": "Cancelar",
"保存": "Salvar",
"删除": "Excluir",
"编辑": "Editar",
"新增": "Novo",
"搜索": "Buscar",
"加载中": "Carregando",
"成功": "Sucesso",
"失败": "Falha",
"音量": "Volume",
"亮度": "Brilho",
"主题": "Tema",
"重启": "Reiniciar",
"固件": "Firmware",
"版本": "Versão",
"网络": "Rede",
"状态": "Status",
"在线": "Online",
"离线": "Offline",
"用户名": "Usuário",
"密码": "Senha",
"手机号": "Celular",
"验证码": "Código",
"登录": "Login",
"注册": "Registro",
"备注": "Observação",
"首页": "Início",
"设置": "Configurações",
"帮助": "Ajuda",
"关于": "Sobre",
"欢迎使用": "Bem-vindo",
"重置密码": "Redefinir Senha",
"验证码发送成功": "Código enviado com sucesso",
"两次输入的密码不一致": "As senhas não coincidem",
"获取验证码": "Obter Código",
"正在加载中": "Carregando...",
"确认要删除吗": "Confirmar exclusão?",
"全选": "Selecionar Tudo",
"操作成功": "Operação realizada com sucesso",
"提示": "Dica",
"清除缓存": "Limpar Cache",
"刷新页面": "Atualizar página",
"暂无数据": "Sem dados",
"创建时间": "Data de Criação",
"操作": "Ações",
"返回": "Voltar",
"你好小智": "Olá Xiaozhi",
"配置角色": "Configurar Papel",

}

def translate():
    if not os.path.exists(GLOSSARY_PATH):
        print("Glossary not found")
        return

    with open(GLOSSARY_PATH, 'r', encoding='utf-8') as f:
        data = json.load(f)

    zh_cn = data.get("zh_CN", {})
    count = 0
    for key, val in zh_cn.items():
        if val == "TODO" or not val:
            # Try to translate using mappings
            # If it's a long string, we might need LLM, but for now let's do common ones
            if key in MAPPINGS:
                zh_cn[key] = MAPPINGS[key]
                count += 1
            else:
                # Placeholder for common patterns or just simple translation
                pass
    
    with open(GLOSSARY_PATH, 'w', encoding='utf-8') as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    
    print(f"Translated {count} strings using local mappings.")

if __name__ == "__main__":
    translate()
